### ISSUE TITLE
Glimmer on the spheres

### ISSUE THREAD

**Issue by lackinganame** [rlawry/earth-tilt#1]
This glimmer is because there are 2 half spheres in that same place.

**Comment by rlawry** [comment]
I must be making a full sphere at some point. It should only be half a rotation.   From 0 to pi, then from pi to 2pi

________________________________
From: Galabeam ***@***.***>
Sent: Monday, October 2, 2023 4:22 PM
To: rlawry/earth-tilt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rlawry/earth-tilt] Glimmer on the spheres (Issue #1)


This glimmer is because there are 2 half spheres in that same place.
